# Project: AlgCode
# Makefile created by Dev-C++ 5.16

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
RES      = AlgCode_private.res
OBJ      = main.o 002移除数组.o $(RES)
LINKOBJ  = main.o 002移除数组.o $(RES)
LIBS     = -L"D:/360Downloads/Dev-Cpp/MinGW64/lib" -L"D:/360Downloads/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -g3
INCS     = -I"D:/360Downloads/Dev-Cpp/MinGW64/include" -I"D:/360Downloads/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/360Downloads/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/8.1.0/include"
CXXINCS  = -I"D:/360Downloads/Dev-Cpp/MinGW64/include" -I"D:/360Downloads/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/360Downloads/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/8.1.0/include" -I"D:/360Downloads/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++"
BIN      = AlgCode.exe
CXXFLAGS = $(CXXINCS) -Wextra -g3 -pipe
CFLAGS   = $(INCS) -Wextra -g3 -pipe
RM       = del /q

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

002移除数组.o: 002移除数组.cpp
	$(CPP) -c 002移除数组.cpp -o 002移除数组.o $(CXXFLAGS)

AlgCode_private.res: AlgCode_private.rc 
	$(WINDRES) -i AlgCode_private.rc --input-format=rc -o AlgCode_private.res -O coff 

